name: Deploy Docsite
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install
        name: Install Dependencies

      - run: yarn build
        name: Build Packages
        env:
          CI: true

      - run: yarn lerna run prepare_for_release --scope @chart-parts/docsite
        name: Build Docsite
      
      - name: Deploy Docsite
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      
      
